# apiVersion: v1
# kind: Service
# metadata:
#   name: dindsvc
#   labels:
#     app: dinddindsvc
# spec:
#   ports:
#   - port: 2375
#     targetPort: 2375  
#     name: dockerd
#   selector:
#     app: dind
#   type: ClusterIP  
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#  name: dind
# spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: dind 
#  template:
#    metadata:
#      labels:
#        app: dind 
#    spec:
#      containers:
#        - name: dind
#          image: "docker:dind"
#          imagePullPolicy: Always
#          command: ["dockerd", "--host", "tcp://0.0.0.0:2375"]
#          securityContext:
#            privileged: true
#      volumes:
#        - name: launcher-storage
#          emptyDir: {}

apiVersion: v1
kind: Namespace
metadata:
  name: self-hosted-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dos-box-runner
  namespace: self-hosted-runners
spec:
  replicas: 1
  template:
    spec:
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true    
      repository: tmtam612/iac
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: "Exists"
        effect: NoSchedule
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: dos-box-runner-autoscaler
  namespace: self-hosted-runners
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: dos-box-runner
  minReplicas: 0
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    scaleUpThreshold: '1'
    scaleDownThreshold: '0'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'        